import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type SupportedLocale = "en-US" | "fr-FR" | "de-DE" | "es-ES" | "ja-JP" | "zh-CN" | "ar" | "he";
export type Catalog = Record<string, string>;
export const LOCALES: Array<{ code: SupportedLocale; name: string; nativeName: string; rtl?: boolean }> = [
  { code: "en-US", name: "English", nativeName: "English" }, { code: "fr-FR", name: "French", nativeName: "Français" }, { code: "de-DE", name: "German", nativeName: "Deutsch" }, { code: "es-ES", name: "Spanish", nativeName: "Español" }, { code: "ja-JP", name: "Japanese", nativeName: "日本語" }, { code: "zh-CN", name: "Chinese", nativeName: "中文" }, { code: "ar", name: "Arabic", nativeName: "العربية", rtl: true }, { code: "he", name: "Hebrew", nativeName: "עברית", rtl: true },
];
const EN: Catalog = { "app.tagline": "Explore what matter can become.", "nav.explore": "Explore", "nav.lab": "Lab", "nav.library": "Library", "nav.profile": "Profile", "system.offline": "Offline mode", "system.retry": "Try again", "ai.copilot": "LATTICE Copilot" };
const TRANSLATIONS: Partial<Record<SupportedLocale, Catalog>> = { "fr-FR": { "app.tagline": "Explorez ce que la matière peut devenir.", "nav.explore": "Explorer", "nav.lab": "Laboratoire", "nav.library": "Bibliothèque", "nav.profile": "Profil", "system.offline": "Mode hors ligne", "system.retry": "Réessayer", "ai.copilot": "LATTICE Copilot" }, "de-DE": { "app.tagline": "Entdecke, was Materie werden kann.", "nav.explore": "Entdecken", "nav.lab": "Labor", "nav.library": "Bibliothek", "nav.profile": "Profil", "system.offline": "Offline-Modus", "system.retry": "Erneut versuchen", "ai.copilot": "LATTICE Copilot" }, "es-ES": { "app.tagline": "Explora en qué puede convertirse la materia.", "nav.explore": "Explorar", "nav.lab": "Laboratorio", "nav.library": "Biblioteca", "nav.profile": "Perfil", "system.offline": "Modo sin conexión", "system.retry": "Reintentar", "ai.copilot": "LATTICE Copilot" }, "ja-JP": { "app.tagline": "物質の可能性を探る。", "nav.explore": "探索", "nav.lab": "ラボ", "nav.library": "ライブラリ", "nav.profile": "プロフィール", "system.offline": "オフラインモード", "system.retry": "再試行", "ai.copilot": "LATTICE Copilot" }, "zh-CN": { "app.tagline": "探索物质的无限可能。", "nav.explore": "探索", "nav.lab": "实验室", "nav.library": "资料库", "nav.profile": "个人资料", "system.offline": "离线模式", "system.retry": "重试", "ai.copilot": "LATTICE Copilot" } };
const KEY = "lattice.locale.v1";
export function resolveLocale(value?: string): SupportedLocale { const exact = LOCALES.find((item) => item.code === value); if (exact) return exact.code; const language = value?.split("-")[0]; return LOCALES.find((item) => item.code.split("-")[0] === language)?.code ?? "en-US"; }
export function isRTL(locale: SupportedLocale) { return locale === "ar" || locale === "he"; }
export function translate(locale: SupportedLocale, key: string) { return TRANSLATIONS[locale]?.[key] ?? EN[key] ?? key; }
type I18nContext = { locale: SupportedLocale; isRTL: boolean; changeLocale: (locale: SupportedLocale) => void; t: (key: string) => string; isHydrated: boolean };
const Context = createContext<I18nContext | null>(null);
export function I18nProvider({ children }: { children: ReactNode }) { const [locale, setLocale] = useState<SupportedLocale>("en-US"); const [isHydrated, setHydrated] = useState(false); useEffect(() => { void AsyncStorage.getItem(KEY).then((stored) => { if (stored) setLocale(resolveLocale(stored)); setHydrated(true); }).catch(() => setHydrated(true)); }, []); const changeLocale = useCallback((next: SupportedLocale) => { setLocale(next); void AsyncStorage.setItem(KEY, next); }, []); const value = useMemo(() => ({ locale, isRTL: isRTL(locale), changeLocale, t: (key: string) => translate(locale, key), isHydrated }), [locale, isHydrated, changeLocale]); return <Context.Provider value={value}>{children}</Context.Provider>; }
export function useI18n() { const value = useContext(Context); if (!value) throw new Error("useI18n must be used inside I18nProvider"); return value; }
