import { ScrollView, StyleSheet, Text, View, Pressable } from "react-native";
import { router } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { useComparison } from "@/lib/comparison-store";

export default function CompareScreen() {
  const { snapshots, removeSnapshot } = useComparison();
  const first = snapshots[0]; const second = snapshots[1];
  const delta = first && second ? second.results.moirePeriod - first.results.moirePeriod : null;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-5"><ScrollView contentContainerStyle={styles.content}><Pressable onPress={() => router.back()} style={styles.back} accessibilityRole="button" accessibilityLabel="Go back"><MaterialIcons name="arrow-back" size={21} color="#F4F8FC" /><Text style={styles.backText}>Library</Text></Pressable><Text style={styles.kicker}>SIDE-BY-SIDE</Text><Text style={styles.title}>Compare experiments.</Text><Text style={styles.intro}>Compare only stored snapshots. Differences are descriptive, not proof of causality.</Text>{snapshots.length < 2 ? <View style={styles.empty}><MaterialIcons name="compare-arrows" size={28} color="#65E6E0" /><Text style={styles.emptyTitle}>Save two snapshots to compare</Text><Text style={styles.emptyText}>Use Compare from the Lab after changing a parameter.</Text></View> : <><View style={styles.columns}>{snapshots.map((snapshot) => <View key={snapshot.id} style={styles.snapshot}><View style={styles.snapshotTop}><Text style={styles.snapshotLabel}>{snapshot.label}</Text><Pressable onPress={() => void removeSnapshot(snapshot.id)} accessibilityRole="button" accessibilityLabel={`Remove ${snapshot.label}`}><MaterialIcons name="close" size={17} color="#70849A" /></Pressable></View><Text style={styles.pair}>{snapshot.parameters.layerA.formula} / {snapshot.parameters.layerB.formula}</Text><Text style={styles.meta}>Twist {snapshot.parameters.twistAngle.toFixed(2)}°</Text><Metric label="Moiré period" value={`${snapshot.results.moirePeriod.toFixed(1)} Å`} /><Metric label="Mismatch" value={`${(snapshot.results.mismatch * 100).toFixed(1)}%`} /></View>)}</View><View style={styles.delta}><Text style={styles.deltaLabel}>MODELED DIFFERENCE</Text><Text style={styles.deltaValue}>{delta === null ? "—" : `${delta >= 0 ? "+" : ""}${delta.toFixed(1)} Å`}</Text><Text style={styles.deltaText}>Change in estimated moiré period from the first snapshot to the second.</Text></View></>}</ScrollView></ScreenContainer>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ content: { paddingTop: 15, paddingBottom: 35 }, back: { flexDirection: "row", alignItems: "center", gap: 8, minHeight: 44 }, backText: { color: "#9FB0C3", fontWeight: "700" }, kicker: { color: "#65E6E0", fontSize: 11, fontWeight: "800", letterSpacing: 1.5, marginTop: 22 }, title: { color: "#F4F8FC", fontSize: 32, fontWeight: "800", marginTop: 8 }, intro: { color: "#9FB0C3", fontSize: 15, lineHeight: 22, marginTop: 10 }, columns: { flexDirection: "row", gap: 10, marginTop: 24 }, snapshot: { flex: 1, backgroundColor: "#0D1B2E", borderWidth: 1, borderColor: "#27415C", borderRadius: 17, padding: 13 }, snapshotTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, snapshotLabel: { color: "#65E6E0", fontSize: 10, fontWeight: "800", letterSpacing: 0.8 }, pair: { color: "#F4F8FC", fontSize: 16, fontWeight: "800", marginTop: 12 }, meta: { color: "#9FB0C3", fontSize: 12, marginTop: 6 }, metric: { borderTopWidth: 1, borderTopColor: "#27415C", marginTop: 14, paddingTop: 10 }, metricLabel: { color: "#70849A", fontSize: 10, fontWeight: "700" }, metricValue: { color: "#F4F8FC", fontSize: 16, fontWeight: "800", marginTop: 4 }, delta: { backgroundColor: "#16152E", borderWidth: 1, borderColor: "#3D3468", borderRadius: 17, padding: 16, marginTop: 16 }, deltaLabel: { color: "#9B8CFF", fontSize: 10, fontWeight: "800", letterSpacing: 1 }, deltaValue: { color: "#F4F8FC", fontSize: 28, fontWeight: "800", marginTop: 8 }, deltaText: { color: "#9FB0C3", fontSize: 12, lineHeight: 18, marginTop: 4 }, empty: { alignItems: "center", backgroundColor: "#0D1B2E", borderWidth: 1, borderColor: "#27415C", borderRadius: 18, padding: 28, marginTop: 27 }, emptyTitle: { color: "#F4F8FC", fontSize: 17, fontWeight: "800", marginTop: 13 }, emptyText: { color: "#9FB0C3", fontSize: 13, lineHeight: 20, textAlign: "center", marginTop: 8 } });
