import { useEffect, useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import Svg, { Circle, Line, Path, Rect } from "react-native-svg";
import { generateMoireSurface, MOIRE_SCENE, normalizeScalar, renderStateForPreferences } from "@/visual3d/analytical";
import { DEFAULT_VISUALIZATION_PREFERENCES, type VisualizationPreferences } from "@/lib/visualization-preferences";
import { loadVisualizationPreferences, saveVisualizationPreferences } from "@/lib/visualization-preferences-store";

export function AnalyticalSurfacePreview({ reducedMotion = false, advanced3DAvailable = false }: { reducedMotion?: boolean; advanced3DAvailable?: boolean }) {
  const [preferences, setPreferences] = useState<VisualizationPreferences>({ ...DEFAULT_VISUALIZATION_PREFERENCES });
  const [hydrated, setHydrated] = useState(false);
  const [storageWarning, setStorageWarning] = useState(false);
  useEffect(() => { let mounted = true; void loadVisualizationPreferences().then((value) => { if (mounted) { setPreferences(value); setHydrated(true); } }).catch(() => { if (mounted) { setHydrated(true); setStorageWarning(true); } }); return () => { mounted = false; }; }, []);
  useEffect(() => { if (!hydrated) return; void saveVisualizationPreferences(preferences).catch(() => setStorageWarning(true)); }, [hydrated, preferences]);

  const state = useMemo(() => ({ ...renderStateForPreferences(reducedMotion, preferences.quality === "low"), ...preferences }), [preferences, reducedMotion]);
  const points = useMemo(() => generateMoireSurface(2, state.quality === "low" ? 7 : state.quality === "high" ? 15 : 11, 0.36), [state.quality]);
  const bounds = useMemo(() => { const values = points.map((point) => point.value); return { min: Math.min(...values), max: Math.max(...values) }; }, [points]);
  const sampledPoints = useMemo(() => points.filter((_, index) => index % Math.round(Math.sqrt(points.length) / 2) === 0), [points]);
  const path = useMemo(() => sampledPoints.map((point, index) => { const x = 28 + ((point.x + 1) / 2) * 264; const y = 118 - ((point.y + 1) / 2) * 78 - point.z * 36; return `${index === 0 ? "M" : "L"}${x.toFixed(1)},${y.toFixed(1)}`; }).join(" "), [sampledPoints]);
  const update = (patch: Partial<VisualizationPreferences>) => setPreferences((current) => ({ ...current, ...patch }));
  const cycleQuality = () => update({ quality: preferences.quality === "low" ? "medium" : preferences.quality === "medium" ? "high" : "low" });

  return <View style={styles.card} accessible accessibilityLabel={`${MOIRE_SCENE.title}. ${MOIRE_SCENE.units}. Validity: ${MOIRE_SCENE.validity}.`}><View style={styles.header}><View><Text style={styles.kicker}>ANALYTICAL PREVIEW</Text><Text style={styles.title}>Moiré scalar surface</Text></View><Text style={styles.badge}>{state.quality.toUpperCase()}</Text></View><Svg width="100%" height={150} viewBox="0 0 320 150"><Rect x="0" y="0" width="320" height="150" rx="14" fill="#091827" />{state.showAxes && <><Line x1="28" y1="119" x2="292" y2="119" stroke="#27415C" strokeWidth="1" /><Line x1="28" y1="119" x2="28" y2="25" stroke="#27415C" strokeWidth="1" /></>}<Path d={path} fill="none" stroke="#65E6E0" strokeWidth="2" opacity={state.reducedMotion ? 0.75 : 0.95} />{sampledPoints.map((point, index) => { const x = 28 + ((point.x + 1) / 2) * 264; const y = 118 - ((point.y + 1) / 2) * 78 - point.z * 36; return <Circle key={`${point.x}-${point.y}-${index}`} cx={x} cy={y} r={2.7} fill="#9B8CFF" opacity={0.45 + normalizeScalar(point.value, bounds.min, bounds.max) * 0.5} />; })}</Svg>{state.showLegend && <View style={styles.legend}><View style={styles.legendDot} /><Text style={styles.axis}>relative contrast</Text><Text style={styles.axis}>x/y normalized</Text></View>}<View style={styles.controls}><Pressable onPress={cycleQuality} style={styles.control} accessibilityRole="button" accessibilityLabel="Cycle analytical preview quality"><Text style={styles.controlText}>Quality: {state.quality}</Text></Pressable><Pressable onPress={() => update({ showAxes: !state.showAxes })} style={[styles.control, !state.showAxes && styles.controlOff]} accessibilityRole="button" accessibilityState={{ selected: state.showAxes }}><Text style={styles.controlText}>Axes {state.showAxes ? "on" : "off"}</Text></Pressable><Pressable onPress={() => update({ showLegend: !state.showLegend })} style={[styles.control, !state.showLegend && styles.controlOff]} accessibilityRole="button" accessibilityState={{ selected: state.showLegend }}><Text style={styles.controlText}>Legend {state.showLegend ? "on" : "off"}</Text></Pressable></View><Text style={styles.note}>{advanced3DAvailable ? "Advanced 3D entitlement available; this screen is the analytical preview." : "Advanced 3D unavailable; showing the local analytical fallback."} Model {MOIRE_SCENE.modelVersion} · {state.reducedMotion ? "motion paused" : "static surface"}</Text>{storageWarning && <Text style={styles.warning}>Visualization preferences could not be saved locally. The current view will still work for this session.</Text>}</View>;
}

const styles = StyleSheet.create({ card: { backgroundColor: "#101C31", borderRadius: 18, borderWidth: 1, borderColor: "#39416A", padding: 15, marginTop: 18 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 12 }, kicker: { color: "#9B8CFF", fontSize: 10, fontWeight: "800", letterSpacing: 1 }, title: { color: "#F4F8FC", fontSize: 17, fontWeight: "800", marginTop: 5 }, badge: { color: "#65E6E0", fontSize: 10, fontWeight: "800", letterSpacing: 1 }, legend: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 8 }, legendDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: "#9B8CFF" }, axis: { color: "#8FA1B8", fontSize: 10 }, controls: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 12 }, control: { borderWidth: 1, borderColor: "#39416A", borderRadius: 9, paddingHorizontal: 9, paddingVertical: 7, backgroundColor: "#0D1B2E" }, controlOff: { opacity: 0.55 }, controlText: { color: "#C7D9E4", fontSize: 10, fontWeight: "800" }, note: { color: "#9FB0C3", fontSize: 11, lineHeight: 16, marginTop: 10 }, warning: { color: "#FFC76B", fontSize: 11, lineHeight: 16, marginTop: 8 } });
